/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

/**
 *
 * @author joao
 */
public class FrmMenuInicial extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuInicial
     */
    public FrmMenuInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        JmCadastrarFerramenta = new javax.swing.JMenu();
        JMFerramenta = new javax.swing.JMenuItem();
        JmCadastrarAmigo = new javax.swing.JMenuItem();
        JmCadastrarEmprestimo = new javax.swing.JMenuItem();
        JMGerenciarFerramenta = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        JMGerenciarAmigo = new javax.swing.JMenuItem();
        JMGerenciarEmprestimo = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        JMRelátorioFerramenta = new javax.swing.JMenuItem();
        JMRelatorioEmprestimo = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JmCadastrarFerramenta.setText("Cadastrar");

        JMFerramenta.setText("Cadastrar Ferramenta");
        JMFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMFerramentaActionPerformed(evt);
            }
        });
        JmCadastrarFerramenta.add(JMFerramenta);

        JmCadastrarAmigo.setText("Cadastrar Amigo");
        JmCadastrarFerramenta.add(JmCadastrarAmigo);

        JmCadastrarEmprestimo.setText("Cadastrar Emprestimo");
        JmCadastrarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmCadastrarEmprestimoActionPerformed(evt);
            }
        });
        JmCadastrarFerramenta.add(JmCadastrarEmprestimo);

        jMenuBar1.add(JmCadastrarFerramenta);

        JMGerenciarFerramenta.setText("Gerenciar");

        jMenuItem2.setText("Gerenciar Ferramentas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        JMGerenciarFerramenta.add(jMenuItem2);

        JMGerenciarAmigo.setText("Gerenciar Amigos");
        JMGerenciarFerramenta.add(JMGerenciarAmigo);

        JMGerenciarEmprestimo.setText("Gerenciar Emprestimos");
        JMGerenciarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMGerenciarEmprestimoActionPerformed(evt);
            }
        });
        JMGerenciarFerramenta.add(JMGerenciarEmprestimo);

        jMenuBar1.add(JMGerenciarFerramenta);

        jMenu5.setText("Relatorios");

        JMRelátorioFerramenta.setText("Relatorio de Ferramentas");
        JMRelátorioFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMRelátorioFerramentaActionPerformed(evt);
            }
        });
        jMenu5.add(JMRelátorioFerramenta);

        JMRelatorioEmprestimo.setText("Relátorio de Emprestimos");
        jMenu5.add(JMRelatorioEmprestimo);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMFerramentaActionPerformed
        FrmCadastroFerramenta janela = new FrmCadastroFerramenta();
        janela.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_JMFerramentaActionPerformed

    private void JmCadastrarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmCadastrarEmprestimoActionPerformed
       FrmCadastroEmprestimo janela = new FrmCadastroEmprestimo();
        janela.setVisible(rootPaneCheckingEnabled); 
    }//GEN-LAST:event_JmCadastrarEmprestimoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void JMGerenciarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMGerenciarEmprestimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMGerenciarEmprestimoActionPerformed

    private void JMRelátorioFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMRelátorioFerramentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMRelátorioFerramentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMFerramenta;
    private javax.swing.JMenuItem JMGerenciarAmigo;
    private javax.swing.JMenuItem JMGerenciarEmprestimo;
    private javax.swing.JMenu JMGerenciarFerramenta;
    private javax.swing.JMenuItem JMRelatorioEmprestimo;
    private javax.swing.JMenuItem JMRelátorioFerramenta;
    private javax.swing.JMenuItem JmCadastrarAmigo;
    private javax.swing.JMenuItem JmCadastrarEmprestimo;
    private javax.swing.JMenu JmCadastrarFerramenta;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
